- name: Check server name vars
  ansible.builtin.assert:
    that:
      - docker_servername is defined and docker_servername | length > 0
      - ghcr_servername is defined and ghcr_servername | length > 0
      - mirrors_servername is defined and mirrors_servername | length > 0
      - nexus_servername is defined and nexus_servername | length > 0
    fail_msg: "Error: Check server name vars"

- name: Gen nexus work dir
  ansible.builtin.file:
    path: "{{ nexus_work_dir }}/conf.d"
    state: directory
    mode: '0755'

- name: Gen index.md files
  ansible.builtin.template:
    src: index.md.j2
    dest: "{{ role_path }}/files/index.md"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Generate index.html from markdown using pandoc
  ansible.builtin.command:
    cmd: >
      pandoc -s -o {{ role_path }}/files/index.html
      {{ role_path }}/files/index.md
      --metadata title="mirrors使用方法"
      --standalone --highlight-style=espresso
      --variable=maxwidth=60em
    creates: ../files/index.html
  delegate_to: localhost
  run_once: true

- name: Copy nginx.conf and index.html to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nexus_work_dir }}/"
    mode: '0644'
  with_fileglob:
    - nginx.conf
    - index.html

- name: Copy conf.d to host
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ nexus_work_dir }}/conf.d/{{ item | basename | replace('.j2', '') }}"
    mode: '0644'
  with_fileglob:
    - "../templates/*.conf.j2"

- name: Copy docker-compose.yaml to host
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ nexus_work_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Del localhost tmp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ role_path }}/files/index.html"
    - "{{ role_path }}/files/index.md"
  delegate_to: localhost
  run_once: true

- name: Start nexus
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/nexus
