- name: Set and Validate host architecture
  ansible.builtin.set_fact:
    host_arch: "{{ ansible_architecture }}"
    host_arch_alias: >-
      {{
        {'x86_64': 'amd64', 'aarch64': 'arm64'}[ansible_architecture] | default('unsupported')
      }}

- name: Fail if unsupported
  ansible.builtin.fail:
    msg: "Unsupported architecture: {{ ansible_architecture }}"
  when: host_arch_alias == 'unsupported'

- name: Mkdir docker conf dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ cli_plugins }}"
    - "/etc/docker/"
    - "/etc/containerd/"

- name: Install binary file to host
  ansible.builtin.include_tasks: "install_binary.yaml"

- name: Copy daemon.json to host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/docker/{{ item }}"
    mode: "0644"
  loop:
    - "daemon.json"
    - "config.toml"

- name: Create systemd file for docker/containerd
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: '0644'
  loop:
    - "containerd.service"
    - "docker.service"

- name: Systemctl daemon_reload
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    daemon_reload: true
  failed_when: false
  loop:
    - "containerd"
    - "docker"

- name: Ensure docker/containerd is running and enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "containerd"
    - "docker"
